blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    # Postのpkであることを明確に記述する
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'), # コメントビューというのもある
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # /diary　※name='index' は view や templates からこの URL を逆引きして呼び出すためのもの
    path('add/', views.AddView.as_view(), name='add'), # /diary/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'), # diary/update/1　※特定のレコードに対して処理を行うので <int:pk> として pk で識別
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'), # /diary/delete/1　※特定のレコードに対して処理を行うので pk で識別
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'), # /diary/detail/1　※特定のレコードに対して処理を行うので pk で識別
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),  # /diary で日記アプリケーション
    path('blog/', include('blog.urls')),  # /blog で、ブログアプリケーション
    path('employee/', include('employee.urls')),  # /employee で、社員管理あぷりけーしょん
]

diary/models.py
from django.db import models
from django.utils import timezone # djangoでは、datetime.now のかわりに、timezone.now で現在日付・時刻を取得する


class Day(models.Model):
    # 格納する情報を整理
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm): # DjangoのModelFormでは強力なValidationを使える

    class Meta: # 入れ子になっているけどこういうものだと思いましょう
        model = Day # Dayモデルと接続し、Dayモデルの内容に応じてformを作ってくれる
        fields = '__all__' # これはすべて指定するやり方。('title', 'text') とタプルで個別に指定することもできる

diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic # 汎用ビューを使うためのもの
from django.urls import reverse_lazy # 汎用ビューでデータベースの変更(CRUD) を行うためのもの
from .forms import DayCreateForm # forms.pyで作ったクラスをimport
from .models import Day # Dayモデルをimport


class IndexView(generic.ListView): # generic の ListViewクラスを継承
    model = Day # 一覧表示させたいモデルを呼び出し
    # （ListViewクラスで呼び出されたモデル名はモデル名(小文字)_list という変数で html 側で扱える
    # URLも自動で探してくれる：アプリ名/モデル名_list.html という名前でtemplateを探して、viewで呼び出したモデルを渡してくれる
    # 「diary/day_list.html」 という URL で呼び出される
    # templateを別名で指定するときは「template_name = 'diary/index.html」と書くが、書かなければ上記ルールで自動
    paginate_by = 3 # 3記事を基準にページネーション（generic.ListViewはデフォルト機能でページネイトに対応している）

class AddView(generic.CreateView):
    model = Day # 作成したいmodelを指定
    form_class = DayCreateForm # 作成したいformを指定（シンプルなモデルフォームを使うときは「fields = '__all__' と直接ここに書いても OK）
    success_url = reverse_lazy('diary:index')
    # success_url：データベースの変更に成功した場合にリダイレクトさせるページ（今回は「アプリ名:逆引きURL」の形で指定し、結果的に urls.py で指定した「''」が返される）
    # reverse_lazy：viewに対応した「URLの文字列」を返す。今回であれば「/diary/」を返してくれる

class UpdateView(generic.UpdateView): # 考え方は AddView とほぼ同じ
    model = Day
    form_class = DayCreateForm # 新規登録時にDayCreateFormを通して行った処理を改めて行うのでDayCreateFormをほぼそのまま活用できるのじゃ
    success_url = reverse_lazy('diary:index')


class DeleteView(generic.DeleteView):
    model = Day
    # forms は必要ないので個別のtemplats で確認などを行う
    success_url = reverse_lazy('diary:index')


class DetailView(generic.DetailView):
    model = Day # pkはurlで指定しているのでここではmodelを呼び出すだけで済む

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <!-- DjangoのURLタグを使って「逆引きURL」で呼び出せる (逆引きで呼び出す方が変更が楽) -->
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
          <!-- superuserでログインしている時だけ表示 -->
          {% if user.is_superuser %}
            <a class="nav-link" href="{% url 'admin:diary_day_add' %}" target="_blank">追加</a>
          {% endif %}
      </nav>
      <!-- このblockの中で各templateの記載内容が呼び出される -->
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <table class="table">
      <tr>
        <th>タイトル</th>
        <td>{{ day.title }}</td>
      </tr>
      <tr>
        <th>本文</th>
        <td>{{ day.text }}</td>
      </tr>
      <tr>
        <th>日付</th>
        <td>{{ day.date }}</td>
      </tr>
  </table>
  <p>こちらのデータを削除します。</p>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <!-- linebreaksbk を入れると改行タグでちゃんと改行して表示されるようになる -->
      <td>{{ day.text | linebreaksbr}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ day.date }}</td>
    </tr>
</table>

{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<p>{{ day.title }}</p>
<!-- actionにはサーバのどのURLに対して情報を送信する -->
<!-- actionを空欄にすると現在開いている URL = /diary/add に値を返すので、views.py の add 関数が再度呼び出されることになる -->
<form action="" method="POST">
  <table class="table">
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>本文</th>
        <td>{{ form.text }}</td>
      </tr>
      <tr>
        <th>日付</th>
        <td>{{ form.date }}</td>
      </tr>
  </table>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th>#</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    {% for day in day_list %}
    <tr>
      <!-- 「url 'アプリ名:逆引きURL' 渡されるモデル.pk」 という描き方 -->
      <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
      <td>{{ day.date }}</td>
      <td>
        <!-- superuserでログインしている時にのみ表示 -->
        {% if user.is_superuser %}
        <!-- HTMLを アプリ名_モデル名_change にすると admin でそのまま編集できる -->
          <a href="{% url 'admin:diary_day_change' day.pk %}" target="_blank">更新</a>
        {% endif %}
      </td>
      <td>
        {% if user.is_superuser %}
          <a href="{% url 'admin:diary_day_delete' day.pk %}" target="_blank">削除</a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<!-- ページネート用のテンプレートを読み込み -->
{% include 'diary/page.html' %}

{% endblock %}

diary/templates/diary/page.html
<nav aria-label="Page navigation">
  <ul class="pagination">
      <!-- 前のページが存在しているかどうかを確認 -->
      {% if page_obj.has_previous %}
        <!-- 前のページが存在している時の処理 -->
        <li class="page-item">
        <!-- URLにクエリを入れる -->
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      
      <!-- 複数ページが存在している時のために各ページ番号を表示させる -->
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
      
      <!-- 次のページが存在しているかどうかの確認 -->
      {% if page_obj.has_next %}
        <li class="page-item">
        <!-- 次のページが存在している場合の処理 -->
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

diary/templates/diary/page4.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>