blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    # Postのpkであることを明確に記述する
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'), # コメントビューというのもある
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),  # /diary で日記アプリケーション
    path('blog/', include('blog.urls')),  # /blog で、ブログアプリケーション
    path('employee/', include('employee.urls')),  # /employee で、社員管理あぷりけーしょん
]

blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """カテゴリ"""

    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.name


class Post(models.Model):
    """ブログの記事"""

    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    # 外部キーとしてCategoryモデルオブジェクトを呼び出す
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Comment(models.Model):
    """ブログのコメント"""

    name = models.CharField('お名前', max_length=30, default='名無し')
    text = models.TextField('本文')
    post = models.ForeignKey(Post, verbose_name='紐づく記事', on_delete=models.PROTECT)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    # 特殊メソッド
    def __str__(self):
        return self.text[:10] # 本文の10文字目までを表示させる

blog/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):

    # *args: 複数の引数をタプルとして受け取る
    # **kwargs: 複数のキーワード引数を辞書として受け取る
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) # 特殊処理を上書き
        for field in self.fields.values():
            # form内のすべてのフィールドのclass属性(css)にform-controlという属性を上書きの形で追加
            field.widget.attrs['class'] = 'form-control'

    # モデルフォームのお約束
    class Meta:
        model = Comment
        # 飛んでくるときには Post の pk がわかっている
        # 一部のフィールドのみを指定
        fields = ('name', 'text')

blog/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from .forms import CommentCreateForm # コメントフォームを呼び出す
from .models import Post, Category, Comment


class IndexView(generic.ListView): # モデルを作ってからListViewとして働きだす
    model = Post
    paginate_by = 10

    # 検索バーにキーワードを入力して検索するための処理
    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at') # created_at を基準にソート（ "-" をつけると降順で並び替え）
        # 呼び出す時に与えられた値をそのままkeywordとして使う
        keyword = self.request.GET.get('keyword')
        if keyword:
            # タイトルで完全一致させるなら queryset = queryset.filter(title=keyword) でよい
            queryset = queryset.filter(
                # 部分一致させるには __icontains と指定し、さらに or 検索をさせるならば Q(xx_cicontains=keyword) | ... とする
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


# 常に右側に表示させるので常に渡す（context_processorsという手段を使う）
class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10

    # 
    def get_queryset(self):
        """
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        """
        category_pk = self.kwargs['pk'] # Category の pk を取得。 url.py で定義した変数を self.kwargs['pk'] で使える
        queryset = Post.objects.order_by('-created_at').filter(category__pk=category_pk) # CategoryそのものではなくCategoryのpkで絞り込み
        return queryset


class DetailView(generic.DetailView):
    model = Post


class CommentView(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm # モデルフォームを今回は使う

    # formの入力内容のチェックに通ったら呼び出される
    def form_valid(self, form):
        post_pk = self.kwargs['post_pk'] # urlに含まれるpkを渡す
        comment = form.save(commit=False)  # この段階ではまだコメントはDBに保存されていないがコメントモデルのインスタンスは作成されているので書き換えられる
        comment.post = get_object_or_404(Post, pk=post_pk) # 保存する前にモデルインスタンスを作成されているので、post属性をURLのpost_pkで指定する
        comment.save()  # ここでDBに保存
        return redirect('blog:detail', pk=post_pk) # urlのpost_pkを使う

blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>ブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">ブログ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          <!-- superuserにログインしているときだけ表示 -->
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
          <!-- ここで入力した値を keyword として格納して views に渡す -->
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">ブログタイトル!</h1>
      <p class="lead">○○に関するブログです</p>
      <hr class="my-2">
    </div>

    <div class="container">
      <div class="row">
        <!-- コンテナ内に記事内容を表示　※左ペインではコンテンツ -->
        <div class="col-md-8">
          
          {% block content %}
          {% endblock %}
        </div>
        <!-- 右ペインではカテゴリを表示 -->
        <div class="col-md-4">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
            {% for category in category_list %}
              <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class="bg-dark text-white text-center py-3">
      <p>あなたの名前</p>  
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="POST">
    <!-- 複数の入力欄が関連したエラーを見つける -->
    {{ form.non_field_errors }}
    <!-- こう書くとform内の各入力欄をformで取り出せる(fieldという名前で取り出そう) -->
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-dark">送信</button>
</form>

{% endblock %}

blog/templates/blog/page.html
<!-- ページングに使用する（見た目はbootstrap） -->
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
          <!-- 自分で定義したテンプレートタグを templatetags 内に入れている -->
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
  <div class="card-body">
    <p>{{ post.created_at }}, {{ post.category }}</p>
    {{ post.text | linebreaksbr | urlize}}
  </div>
</div>

<!-- post.comment_set.all で post に紐付いたコメントを自動的にすべて取得する（定型的な書き方） -->
{% for comment in post.comment_set.all %}
  <p>
    {{ comment.name }}<br>
    {{ comment.text | linebreaksbr }}
  </p>
{% endfor %}

<!-- 記事の pk を渡しながらフォームを呼び出す -->
<a class="btn btn-dark" href="{% url 'blog:comment' post.pk %}">コメント投稿ページへ</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in post_list %}
  <div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
    <div class="card-body">
      <p>{{ post.created_at }}, {{ post.category }}</p>
      <a href="{% url 'blog:detail' post.pk %}" class="btn btn-dark">続きを読む</a>
    </div>
  </div>
{% endfor %}

{% include 'blog/page.html' %}

{% endblock %}